from .jsonable import Jsonable
from .taskgroup import TaskGroup

class Task(Jsonable):
    """
    The vscode task.
    """

    def __init__(self, label, command, type, args, group, dependsOn, isBackground):
        # type: (str, str, str, list[str], TaskGroup, list[str], bool) -> TaskGroup
        self.label = label
        self.command = command
        self.type = type
        self.args = args
        self.group = group
        self.dependsOn = dependsOn
        self.isBackground = isBackground


class TaskBuilder:
    """
    Builder for the Task
    """

    def __init__(self, label):
        # type: (str) -> TaskBuilder
        self._label = label
        self._command = "" # type: str
        self._args = [] # type: list[str]
        self._type = "shell" # type: str
        self._group = "none" # type: TaskGroup
        self._dependsOn = [] # type: list[str]
        self._isBackground = False # type: bool

    def command(self, command):
        self._command = command
        return self

    def args(self, arg):
        self._args.append(arg)
        return self

    def type(self, type):
        self._type = type
        return self

    def group(self, group):
        self._group = group
        return self

    def isBackground(self, isBackground):
        self._isBackground = isBackground
        return self

    def dependsOn(self, task_label):
        self._dependsOn.append(task_label)
        return self

    def build(self):
        return Task(
            label=self._label,
            command=self._command,
            type=self._type,
            args=self._args,
            group=self._group,
            dependsOn=self._dependsOn,
            isBackground=self._isBackground,
        )

class Tasks(Jsonable):
    def __init__(self, version="2.0.0", tasks=[]):
        # type: (str, list[Task]) -> Tasks
        self.description = "This file is generated by the user script. Editing this file directly is not recommended, as changes may be overwritten by subsequent script executions."
        self.version = version
        self.tasks = tasks
